name: Notify when there are changes in main

on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  notify:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Send TG Reminder
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TG_TO }}
          token: ${{ secrets.TG_NOTIFY_BOT_TOKEN }}
          message_thread_id: ${{ secrets.TG_DEBUG_THREAD }}
          message: |
            <b>[CHANGES TO MAIN BRANCH]</b>

            <b>PR Title</b>: ${{ github.event.pull_request.title }}
            <b>PR Author</b>: ${{ github.event.pull_request.user.name }}
            <b>PR URL</b>: ${{ github.event.pull_request.url }}

            The main branch has been updated. Please pull/merge from the latest version of main.
